# Generated by Django 4.1.4 on 2023-01-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='subcomment',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
